In [1]:
import numpy as np
print("Numpy Version is: {}".format(np.__version__))

Numpy Version is: 1.15.1


In [23]:
# Input size: X.shape = [11, 11, 4], P = 0, F = 5, S = 2; V = (W - F + 2P) / S + 1 = 4
# This example is for a single filter model
x = np.random.randn(11, 11, 4)
w_0 = np.random.randn(5, 5, 4)
v_0 = np.zeros((4, 4))
b_0 = np.random.rand()
S = 2
F = 5

# Calculate V
for x_axis in range(0, x.shape[0] - F + 1, S):
    for y_axis in range(0, x.shape[1] - F + 1, S):
        v_0[int(x_axis/2), int(y_axis/2)] = np.sum(w_0 * x[x_axis: x_axis + F, y_axis: y_axis + F, :]) + b_0

print(v_0)

[[ 18.86053931   4.33237186  15.00591121 -11.508311  ]
 [  2.95449858  -0.60417067  -0.93305985 -21.45686363]
 [ -9.05277224  18.00819198  -4.41512342  -4.85612234]
 [ -6.03751794 -15.78549953  -6.52087038   7.5229798 ]]


In [30]:
# This example is for a 3 filters model, W = [F, F, depth, filter_number], V = [4, 4, depth_number]
x = np.random.randn(11, 11, 4)
W = np.random.randn(5, 5, 4, 3)
V = np.zeros((4, 4, 3))
b = np.random.rand(3)
S = 2
F = 5

# Calculate V
for filter_number in range(W.shape[3]):
    for x_axis in range(0, x.shape[0] - F + 1, S):
        for y_axis in range(0, x.shape[1] - F + 1, S):
            V[int(x_axis/2), int(y_axis/2), filter_number] = np.sum(W[:, :, :, filter_number] * x[x_axis: x_axis + F, y_axis: y_axis + F, :]) + b[filter_number]

print(V)

[[[-10.69223916 -11.14168332 -19.61065674]
  [  9.22605173  -0.82847608  -0.59606155]
  [ 10.41257952  -0.36497088  17.02338508]
  [  1.05475977   8.60318967   4.11042429]]

 [[ -3.29661855   3.50735857   3.11040782]
  [ -0.5298682   -4.08589025   6.03104306]
  [ -1.00523837  -3.0662166   -4.91558761]
  [ 12.92331044  10.58203423   0.39755849]]

 [[  2.79534289   2.1083276    8.8057582 ]
  [ -0.29071316  -4.16627692  -5.81651497]
  [ 15.27787     11.07114124  24.81695363]
  [  7.96520958   6.9190961  -25.66827631]]

 [[  1.84940761   8.2867065   -0.7890902 ]
  [  8.36121312   4.64679653   7.52725648]
  [  0.47586724   5.62563636  11.17604078]
  [  5.93501036  -3.89266434  -3.79098343]]]
